sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t csanchez24/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true csanchez24/docker-react npm run test
